{{--
    Rendered by dompdf, not the browser — so this template deliberately does
    not extend the app layout and does not use Tailwind. dompdf supports only
    a narrow slice of CSS, so everything here is plain, inline-ish rules.
    Mirrors resources/views/reports/pdf.blade.php's conventions.
--}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Flag Report #{{ $alert->id }}</title>
    <style>
        @page { margin: 26px 30px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1a1a2e; font-size: 10px; }

        .head { border-bottom: 2px solid #e17055; padding-bottom: 10px; margin-bottom: 14px; }
        .brand { font-size: 17px; font-weight: bold; color: #e17055; letter-spacing: -0.4px; }
        .title { font-size: 14px; font-weight: bold; margin-top: 3px; }
        .desc  { font-size: 9px; color: #636e72; margin-top: 3px; }

        .meta { width: 100%; margin-bottom: 16px; font-size: 9px; color: #636e72; }
        .meta td { padding: 1px 0; }
        .meta .k { color: #b2bec3; width: 78px; }

        .sev {
            display: inline-block; padding: 2px 8px; border-radius: 3px;
            font-size: 8.5px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.4px;
        }
        .sev-low { background: #fff7dc; color: #a17c00; }
        .sev-medium { background: #ffe9d6; color: #b45309; }
        .sev-high { background: #fde2e2; color: #b91c1c; }

        table.detail { width: 100%; border-collapse: collapse; margin-top: 6px; }
        table.detail th {
            background: #faf9f7;
            border-bottom: 1.2px solid #e17055;
            text-align: left;
            padding: 6px 7px;
            font-size: 8.5px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
            color: #5c2d1b;
            width: 34%;
        }
        table.detail td {
            padding: 6px 7px;
            border-bottom: 0.6px solid #ececec;
            font-size: 9.5px;
        }

        .notes { margin-top: 16px; }
        .notes .label { font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.4px; color: #5c2d1b; margin-bottom: 4px; }
        .notes .body { font-size: 9.5px; color: #1a1a2e; background: #faf9f7; padding: 10px; border-radius: 3px; }

        .foot {
            position: fixed; bottom: -12px; left: 0; right: 0;
            font-size: 8px; color: #b2bec3; text-align: center;
        }
    </style>
</head>
<body>
    <div class="head">
        <div class="brand">NITA</div>
        <div class="title">Flag Report #{{ $alert->id }}</div>
        <div class="desc">Discrepancy alert detail — {{ $alert->branch->name ?? 'Unknown Branch' }}</div>
    </div>

    <table class="meta">
        <tr><td class="k">Generated</td><td>{{ $generatedAt }}</td></tr>
        <tr><td class="k">Generated by</td><td>{{ $generatedBy }}</td></tr>
        <tr><td class="k">Flagged on</td><td>{{ $alert->created_at->format('M d, Y g:i A') }}</td></tr>
    </table>

    <table class="detail">
        <tr><th>Branch</th><td>{{ $alert->branch->name ?? 'Unknown Branch' }}</td></tr>
        <tr><th>Ingredient</th><td>{{ $alert->ingredient->name ?? 'Unknown' }}</td></tr>
        <tr><th>Type</th><td>{{ ucfirst(str_replace('_', ' ', $alert->type ?? 'Discrepancy')) }}</td></tr>
        <tr>
            <th>Severity</th>
            <td><span class="sev sev-{{ $alert->severity }}">{{ ucfirst($alert->severity) }}</span></td>
        </tr>
        <tr><th>Status</th><td>{{ ucfirst($alert->status) }}</td></tr>
        <tr><th>Expected Value</th><td>{{ $alert->expected_value !== null ? number_format((float) $alert->expected_value, 3) : '—' }}</td></tr>
        <tr><th>Actual Value</th><td>{{ $alert->actual_value !== null ? number_format((float) $alert->actual_value, 3) : '—' }}</td></tr>
        <tr><th>Variance</th><td>{{ $alert->variance !== null ? number_format((float) $alert->variance, 3) : '—' }}</td></tr>
        @if ($alert->shiftLog)
            <tr><th>Reported During Shift</th><td>{{ $alert->shiftLog->user->name ?? '—' }} — {{ optional($alert->shiftLog->shift_start)->format('M d, Y g:i A') ?? '—' }}</td></tr>
        @endif
    </table>

    @if ($alert->details)
        <div class="notes">
            <div class="label">Notes</div>
            <div class="body">{{ $alert->details }}</div>
        </div>
    @endif

    <div class="foot">NITA — Flag Report #{{ $alert->id }} · {{ $generatedAt }}</div>
</body>
</html>
