{{--
    Rendered by dompdf, not the browser — so this template deliberately does
    not extend the app layout and does not use Tailwind. dompdf supports only
    a narrow slice of CSS, so everything here is plain, inline-ish rules.
--}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $label }} Report</title>
    <style>
        @page { margin: 26px 30px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1a1a2e; font-size: 10px; }

        .head { border-bottom: 2px solid #e17055; padding-bottom: 10px; margin-bottom: 14px; }
        .brand { font-size: 17px; font-weight: bold; color: #e17055; letter-spacing: -0.4px; }
        .title { font-size: 14px; font-weight: bold; margin-top: 3px; }
        .desc  { font-size: 9px; color: #636e72; margin-top: 3px; }

        .meta { width: 100%; margin-bottom: 12px; font-size: 9px; color: #636e72; }
        .meta td { padding: 1px 0; }
        .meta .k { color: #b2bec3; width: 78px; }

        table.data { width: 100%; border-collapse: collapse; }
        table.data th {
            background: #faf9f7;
            border-bottom: 1.2px solid #e17055;
            text-align: left;
            padding: 6px 7px;
            font-size: 8.5px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
            color: #5c2d1b;
        }
        table.data td {
            padding: 5px 7px;
            border-bottom: 0.6px solid #ececec;
            font-size: 9.5px;
        }
        table.data tr:nth-child(even) td { background: #fcfbfa; }

        .empty { padding: 24px; text-align: center; color: #b2bec3; font-size: 10px; }
        .foot {
            position: fixed; bottom: -12px; left: 0; right: 0;
            font-size: 8px; color: #b2bec3; text-align: center;
        }
    </style>
</head>
<body>
    <div class="head">
        <div class="brand">NITA</div>
        <div class="title">{{ $label }} Report</div>
        <div class="desc">{{ $description }}</div>
    </div>

    <table class="meta">
        <tr><td class="k">Generated</td><td>{{ $generatedAt }}</td></tr>
        <tr><td class="k">Generated by</td><td>{{ $generatedBy }}</td></tr>
        <tr><td class="k">Scope</td><td>{{ $scope }}</td></tr>
        <tr><td class="k">Rows</td><td>{{ count($rows) }}</td></tr>
    </table>

    @if (empty($rows))
        <div class="empty">No data available for this report.</div>
    @else
        <table class="data">
            <thead>
                <tr>@foreach ($columns as $col)<th>{{ $col }}</th>@endforeach</tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                    <tr>@foreach ($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="foot">NITA — {{ $label }} Report · {{ $generatedAt }}</div>
</body>
</html>
